name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code download
        uses: actions/checkout@v4

      - name: Java 17 setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle install
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'

      - name: gradlew fix
        run: |
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew

      - name: APK build
        run: ./gradlew assembleDebug --stacktrace

      - name: APK upload
        uses: actions/upload-artifact@v4
        with:
          name: PrivacyBrowser-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
